seed: 42
data_dir: "data/raw/DOW30"
output_dir: "outputs"
trading_days_path: "data/tradingdays(2013-2025).csv"

tickers: [
  "MMM", "AXP", "AMGN", "AMZN", "AAPL",
  "BA", "CAT", "CVX", "CSCO", "KO",
  "DIS", "GS", "HD", "HON", "IBM",
  "JNJ", "JPM", "MCD", "MRK", "MSFT",
  "NKE", "NVDA", "PG", "CRM", "SHW",
  "TRV", "UNH", "VZ", "V", "WMT"
]

start_date: "2019-01-01"
end_date: "2025-12-31"
backtest_start_date: "2020-01-01"

add_vix: False
prediction_return_clip: null
prediction_return_rescale_range: [-0.2, 0.2]
feature_normalization: True
save_feature_contribution: True

model_type: "markowitz"
pred_type: "linear"

hyperparams:
  fee_rate: 0.005
  window_months: 12
  epochs: 20
  lr: 0.001
  batch_size: 32
  rebalance_freq: "MS"
  label_window: 21
  context_history: 20
  weight_adjust_delta: 0.1

model_args:
  alpha: 0.95
  lambda_cvar: 1.0
  lambda_risk: 1.0
  cov_history: 220
  cov_reg: 0.000001
  budget: 1.0

baseline_args:
  risk_aversion: 10.0
  po_pred_epochs: 30
  po_pred_lr: 0.001

